// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/icons/IconShowcase.tsx": () => import("../components/mockups/icons/IconShowcase.tsx"),
  "./components/mockups/outro/KineticType.tsx": () => import("../components/mockups/outro/KineticType.tsx"),
  "./components/mockups/outro/LiveNetwork.tsx": () => import("../components/mockups/outro/LiveNetwork.tsx"),
  "./components/mockups/outro/SunriseInversion.tsx": () => import("../components/mockups/outro/SunriseInversion.tsx")
};
